# Generated by Django 5.1.2 on 2024-10-21 22:00

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_picture_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="user-d9989b0e-8ff7-11ef-aab5-f020ff234df7",
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                fields=("user", "following_user"), name="user_following_user_unique"
            ),
        ),
    ]
